### ISSUE TITLE
Add a back button to the signup page for facebook

### ISSUE THREAD

**Issue by Nicorules** [Nicorules/CaptionIt#9]

**Comment by MukeshMuteja** [comment]
Hi Nicolas, 
Signin and signup buttons are touchable. User can move to signin and signup viewcontroller by clicking on them. Please let me know where you want to add button.

**Comment by Nicorules** [comment]
Hi Mukesh! It would be beneficial to include a "back button" to the yellow
screen that appears after the user signsup with facebook. When the user
decides to signup with email, a back button does appear, but when signingup
with facebook the user is only prompted to input his username. For
navigation sake there should be a back button in that screen also.
Thanks Mukesh!

**Comment by veeranjain04** [comment]
Hi Nicolas,
Please check code is pushed.
